### ISSUE TITLE
dotfileのインストールの短縮

### ISSUE THREAD

**Issue by takayan660** [takayan660/dotfiles#1]
[ドットファイルを GitHub に置き、インストールを自動化した話](https://gist.github.com/cohei/40cd436a87edc524ab36)

上記のように、コマンド一つでインストールできるようにする。

**Comment by tAkayan660** [comment]
[ドットファイルを GitHub に置き、インストールを自動化した話](https://gist.github.com/cohei/40cd436a87edc524ab36)

上記の用なサイトのように、コマンド一つでインストールできるようにする。

**Comment by takayan660** [comment]
install.shに以下のように記入して，READMEに書かれているようにすればインストールがすべて終わるように出来たので，Closeする．<br>

```
git clone https://github.com/tAkayan660/dotfiles.git
cd dotfiles/.emacs.d/public_repos/
git clone https://github.com/ancane/emacs-nav.git
git clone https://github.com/auto-complete/popup-el.git
```

**Comment by takayan660** [comment]
以下のコマンドを入力するとインストールできるようになっている.
`curl https://raw.githubusercontent.com/tAkayan660/dotfiles/master/install.sh | bash`
